package:
  name: coincurve
  # When updating, check setup.py and update chaquopy-secp256k1 as well:
  # * Commit ID and version number in meta.yaml
  # * configure script arguments in build.sh
  version: "21.0.0"

build:
  number: 1

requirements:
  build:
    - cmake 3.28.1
    - pkgconfig 1.3.1
  host:
    - chaquopy-secp256k1 20191011
    - python
